In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [2]:
ficoscores = np.random.randint(350,850,250)
ficoscores

array([659, 462, 840, 583, 609, 642, 418, 733, 393, 504, 757, 701, 611,
       418, 674, 559, 844, 842, 529, 519, 392, 476, 676, 590, 704, 544,
       373, 460, 458, 762, 460, 692, 376, 628, 820, 619, 359, 719, 404,
       415, 506, 807, 627, 388, 487, 628, 593, 629, 587, 407, 710, 588,
       679, 680, 778, 707, 362, 646, 503, 683, 464, 790, 461, 723, 367,
       394, 450, 754, 713, 519, 612, 360, 508, 443, 476, 578, 518, 661,
       554, 669, 424, 459, 705, 646, 474, 747, 721, 640, 432, 537, 770,
       537, 834, 350, 639, 798, 514, 350, 471, 637, 798, 656, 503, 822,
       716, 708, 568, 826, 432, 699, 359, 643, 466, 410, 372, 832, 410,
       573, 559, 751, 524, 730, 777, 595, 733, 652, 620, 649, 672, 442,
       516, 836, 567, 753, 794, 400, 779, 475, 612, 480, 822, 675, 368,
       510, 584, 633, 409, 465, 582, 506, 386, 448, 359, 379, 646, 390,
       662, 697, 571, 638, 474, 735, 451, 505, 537, 502, 554, 457, 524,
       596, 771, 622, 734, 775, 785, 530, 388, 671, 659, 535, 699, 744,
       375, 594, 392, 543, 410, 378, 464, 387, 828, 782, 719, 592, 709,
       726, 638, 843, 767, 706, 847, 439, 494, 662, 492, 506, 519, 657,
       396, 731, 410, 450, 746, 604, 552, 770, 658, 523, 481, 546, 806,
       499, 816, 804, 642, 617, 683, 737, 788, 492, 434, 783, 824, 777,
       841, 704, 821, 434, 440, 780, 574, 506, 583, 736, 398, 768, 773,
       755, 426, 662])

In [3]:
length_of_employment = np.random.randint(low=0, high=60, size = 250)
length_of_employment

array([18, 22, 32,  1,  7, 19, 41, 42,  0, 58, 49, 18,  6, 56, 59,  7,  5,
       22,  2, 25, 22,  5, 16, 12,  1, 49, 34, 28, 26,  8,  5, 34, 38, 20,
       55, 56, 49, 26, 29,  5, 32, 18, 17, 20, 10, 48, 43,  9, 59, 27, 49,
        6, 16, 23, 10,  8, 23, 45,  0, 49, 34, 41,  7, 36, 25, 29, 14, 16,
       32, 12, 37, 21, 27, 22, 48, 53, 35, 53,  9, 47, 10,  6, 20, 57, 28,
       35, 56,  3, 34,  5, 21, 52, 32, 37,  9,  6, 30,  6, 38, 46, 34,  4,
       59, 32, 20, 32, 58, 21, 22, 26, 41, 39, 24, 37, 34, 20,  2, 48, 50,
       51, 14, 34, 27, 11, 59, 46, 12, 53, 22, 29, 50,  3, 57, 47, 16,  8,
       25,  6, 14, 11, 20, 38, 51, 59, 16, 32, 26, 32, 59, 19, 16, 32, 20,
       48, 52, 27, 32, 14, 23, 17, 57, 40, 39, 56, 26, 54,  2,  7, 28, 44,
       33,  9,  4, 11, 11,  8, 13, 32,  4, 52, 18, 26, 48, 18, 27, 37, 52,
       40, 27, 30, 11,  7, 47, 21,  0,  0, 55, 33, 16, 12, 26, 20,  8, 50,
       44, 39, 35,  1, 46, 40,  1, 49, 30, 49, 17, 40, 55,  9, 14, 52, 38,
       27, 12, 38, 39, 26, 25,  2, 41, 40, 23, 56, 26, 10, 14, 21, 56,  9,
       20, 49, 30, 52, 19, 33, 52, 57, 34, 48, 57, 19])

In [4]:
length_of_current_residency = np.random.randint(low=0, high=36, size=250)
length_of_current_residency

array([20, 26, 22, 34, 30, 32, 22, 35,  0, 11, 13, 15, 20, 18, 14, 15,  7,
       12, 24,  3,  0, 27, 19,  4, 22, 35, 35, 16, 19,  4, 16, 16,  5, 28,
       18,  3,  0, 18, 18,  4,  4, 35,  5,  5, 15,  4,  0, 22, 10,  4,  4,
       34, 32,  3, 18, 18, 15, 17,  0, 34, 15, 30, 13, 22,  3, 20, 28, 23,
        0, 15, 15, 13, 34, 19, 16,  4, 26, 31, 15, 19, 26, 28,  8, 29, 16,
       32, 33,  8, 10, 15,  5,  4, 30, 14, 34,  9,  7, 13, 34, 27, 16, 12,
       29, 35,  0, 20, 17, 22, 19, 10, 15, 21, 26, 24, 19,  1, 32,  5, 18,
       32,  9, 35, 28,  7, 26,  7,  6,  2, 35,  5,  1, 22, 19,  5, 25, 13,
        3, 27,  5, 13, 14, 13, 34, 27, 24, 32, 34, 11,  7, 25, 25, 34,  0,
        0,  5, 23,  6,  0, 24, 20, 24,  3, 19, 16, 12, 12, 22, 19,  2, 18,
        3,  8, 34,  8, 25, 28, 12,  3, 34, 21, 11, 32,  6, 21, 18, 23, 25,
       33, 21, 15, 27,  0, 30, 28, 18, 20, 25, 11, 32,  5, 24, 22,  8,  1,
       23,  1, 18, 14,  5, 35,  1, 28,  6, 15, 33, 34, 34, 15, 34,  8, 13,
       26, 30,  7, 20, 29, 34,  1, 25,  3,  1, 33, 14, 11, 31, 16,  5, 18,
        8,  3, 10, 24,  5, 23,  4, 14,  4,  9,  8,  5])

In [5]:
total_monthly_income = np.random.randint(2000,10000,250)
total_monthly_income

array([2819, 3103, 7440, 4570, 6256, 9377, 4160, 2791, 8472, 5448, 8227,
       4249, 7978, 7530, 5419, 7943, 8379, 9228, 3574, 2033, 5996, 4737,
       2613, 2764, 6634, 5163, 4079, 8366, 2336, 3890, 5317, 7058, 9964,
       3600, 9184, 9037, 6125, 4716, 7818, 6562, 6196, 3096, 6613, 4850,
       2823, 8142, 4408, 5459, 2696, 9616, 2771, 3452, 7019, 3836, 6119,
       7213, 8605, 9824, 6451, 5254, 3106, 7879, 2577, 6556, 5793, 4016,
       4854, 6515, 9069, 8172, 3932, 4964, 7504, 7356, 4178, 3066, 7380,
       5619, 3588, 5679, 8519, 7721, 9547, 6667, 7433, 3880, 5335, 8931,
       7764, 8378, 9728, 7835, 8965, 4902, 7614, 4185, 4216, 6824, 5737,
       7929, 3871, 3312, 9574, 7885, 2417, 3679, 2498, 8094, 8563, 8583,
       7190, 7700, 9824, 5118, 9185, 7118, 5617, 7432, 9717, 2617, 8957,
       8446, 8376, 5265, 7431, 4321, 7911, 5853, 4695, 4777, 6785, 8174,
       5348, 6851, 9837, 4590, 3441, 5518, 7976, 3179, 6819, 6399, 7176,
       9446, 4802, 9574, 6105, 5115, 6391, 5948, 5011, 8376, 7306, 8456,
       3399, 9307, 7823, 6075, 5804, 2590, 4389, 7404, 6711, 3284, 5331,
       4849, 4504, 7809, 8582, 6380, 4513, 5824, 3479, 4693, 6791, 5066,
       8859, 7741, 8326, 2613, 4414, 6885, 3731, 9865, 2184, 4004, 3898,
       6967, 9868, 9650, 6628, 6600, 2260, 6560, 7252, 2459, 7703, 3572,
       2099, 3583, 9726, 2857, 3047, 9739, 9233, 5349, 4256, 2914, 4149,
       3859, 4298, 2785, 6654, 3439, 9922, 8694, 8342, 9317, 5384, 8642,
       6637, 8231, 7114, 8687, 8384, 5615, 3744, 3413, 5030, 5916, 9836,
       5961, 7296, 8439, 9141, 9459, 3953, 6811, 3818, 5065, 6612, 3070,
       8273, 9418, 8893, 8858, 5827, 4076, 4663, 9884])

In [6]:
debt_to_income_ratio = np.random.uniform(low=0.0, high=1, size=250)
debt_to_income_ratio = debt_to_income_ratio * 100

In [7]:
main = pd.DataFrame(data=[ficoscores,length_of_employment,length_of_current_residency,total_monthly_income,debt_to_income_ratio]).T
main

          0      1      2        3      4
0   659.000 18.000 20.000 2819.000 55.049
1   462.000 22.000 26.000 3103.000 46.777
2   840.000 32.000 22.000 7440.000 45.944
3   583.000  1.000 34.000 4570.000 70.460
4   609.000  7.000 30.000 6256.000 18.644
5   642.000 19.000 32.000 9377.000 95.537
6   418.000 41.000 22.000 4160.000  3.656
7   733.000 42.000 35.000 2791.000 40.004
8   393.000  0.000  0.000 8472.000 70.733
9   504.000 58.000 11.000 5448.000  4.860
10  757.000 49.000 13.000 8227.000 90.100
11  701.000 18.000 15.000 4249.000 78.373
12  611.000  6.000 20.000 7978.000 51.372
13  418.000 56.000 18.000 7530.000 62.358
14  674.000 59.000 14.000 5419.000 75.976
15  559.000  7.000 15.000 7943.000 19.504
16  844.000  5.000  7.000 8379.000  7.764
17  842.000 22.000 12.000 9228.000 63.138
18  529.000  2.000 24.000 3574.000 63.913
19  519.000 25.000  3.000 2033.000 78.661
20  392.000 22.000  0.000 5996.000 64.762
21  476.000  5.000 27.000 4737.000 22.661
22  676.000 16.000 19.000 2613.000 56.630
23  590.000 12.000  4.000 2764.000 61.196
24  704.000  1.000 22.000 6634.000 71.298
25  544.000 49.000 35.000 5163.000 37.015
26  373.000 34.000 35.000 4079.000 50.788
27  460.000 28.000 16.000 8366.000 33.041
28  458.000 26.000 19.000 2336.000 83.415
29  762.000  8.000  4.000 3890.000 78.644
..      ...    ...    ...      ...    ...
220 806.000 38.000 13.000 6637.000 57.122
221 499.000 27.000 26.000 8231.000 67.981
222 816.000 12.000 30.000 7114.000 96.861
223 804.000 38.000  7.000 8687.000 87.234
224 642.000 39.000 20.000 8384.000 10.357
225 617.000 26.000 29.000 5615.000 71.618
226 683.000 25.000 34.000 3744.000 11.186
227 737.000  2.000  1.000 3413.000 22.220
228 788.000 41.000 25.000 5030.000 62.147
229 492.000 40.000  3.000 5916.000 37.307
230 434.000 23.000  1.000 9836.000 83.741
231 783.000 56.000 33.000 5961.000 99.861
232 824.000 26.000 14.000 7296.000 84.143
233 777.000 10.000 11.000 8439.000 84.041
234 841.000 14.000 31.000 9141.000 60.503
235 704.000 21.000 16.000 9459.000 29.851
236 821.000 56.000  5.000 3953.000 29.004
237 434.000  9.000 18.000 6811.000 41.751
238 440.000 20.000  8.000 3818.000 44.427
239 780.000 49.000  3.000 5065.000 93.794
240 574.000 30.000 10.000 6612.000 54.528
241 506.000 52.000 24.000 3070.000 61.403
242 583.000 19.000  5.000 8273.000 45.225
243 736.000 33.000 23.000 9418.000 51.170
244 398.000 52.000  4.000 8893.000 62.906
245 768.000 57.000 14.000 8858.000 81.625
246 773.000 34.000  4.000 5827.000 34.915
247 755.000 48.000  9.000 4076.000 23.250
248 426.000 57.000  8.000 4663.000  6.435
249 662.000 19.000  5.000 9884.000 76.256

[250 rows x 5 columns]

In [8]:
main.to_csv("dataset2.csv")