In [43]:
import numpy as np
import pandas as pd
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [44]:
ficoscores = np.random.randint(350,850,500)
ficoscores

array([593, 744, 845, 624, 832, 460, 541, 442, 721, 664, 478, 703, 735,
       691, 411, 427, 775, 449, 543, 791, 532, 768, 845, 560, 401, 468,
       751, 619, 633, 673, 642, 788, 791, 557, 799, 403, 759, 682, 849,
       380, 565, 480, 600, 799, 748, 522, 812, 788, 579, 744, 462, 599,
       374, 394, 596, 385, 810, 434, 721, 692, 447, 419, 580, 523, 646,
       613, 604, 409, 436, 764, 508, 814, 392, 366, 454, 749, 739, 837,
       767, 772, 572, 616, 697, 553, 812, 376, 559, 507, 552, 623, 628,
       700, 685, 779, 387, 716, 375, 655, 553, 714, 606, 802, 610, 577,
       822, 823, 489, 819, 831, 849, 462, 656, 570, 660, 576, 446, 595,
       366, 487, 831, 679, 571, 573, 688, 692, 539, 520, 651, 357, 628,
       763, 663, 433, 657, 461, 666, 510, 785, 509, 460, 731, 479, 586,
       416, 619, 467, 625, 742, 762, 640, 781, 527, 784, 446, 808, 558,
       474, 422, 507, 734, 658, 566, 639, 819, 752, 774, 826, 490, 528,
       773, 645, 785, 658, 511, 454, 426, 514, 616, 514, 589, 379, 544,
       477, 407, 686, 370, 804, 761, 647, 687, 803, 422, 391, 706, 510,
       568, 564, 613, 642, 517, 697, 541, 473, 385, 400, 467, 495, 466,
       430, 389, 620, 516, 466, 558, 357, 429, 668, 666, 783, 410, 600,
       825, 601, 618, 537, 497, 773, 568, 442, 718, 417, 768, 575, 354,
       468, 791, 682, 384, 478, 612, 735, 444, 711, 836, 518, 423, 376,
       371, 727, 430, 751, 834, 608, 515, 478, 758, 441, 668, 797, 485,
       721, 430, 508, 498, 416, 695, 374, 656, 497, 831, 710, 463, 829,
       566, 592, 465, 502, 792, 841, 590, 568, 773, 724, 711, 624, 651,
       789, 415, 573, 816, 739, 526, 603, 569, 643, 383, 703, 834, 468,
       787, 727, 524, 848, 632, 643, 364, 529, 509, 844, 520, 355, 840,
       474, 652, 576, 777, 684, 679, 536, 469, 429, 812, 466, 731, 645,
       702, 519, 370, 504, 746, 379, 768, 442, 596, 371, 642, 766, 564,
       640, 516, 598, 529, 585, 807, 755, 556, 764, 795, 768, 767, 409,
       590, 547, 827, 472, 606, 682, 676, 606, 439, 595, 629, 453, 832,
       629, 639, 605, 797, 739, 397, 803, 604, 452, 451, 840, 779, 775,
       437, 361, 521, 713, 671, 470, 440, 369, 471, 522, 717, 403, 703,
       575, 431, 763, 489, 494, 574, 379, 670, 677, 729, 383, 658, 404,
       691, 736, 719, 443, 585, 563, 562, 361, 536, 355, 782, 535, 796,
       517, 607, 725, 502, 708, 392, 668, 823, 459, 748, 393, 422, 757,
       586, 520, 515, 743, 405, 618, 498, 426, 752, 548, 575, 599, 709,
       486, 403, 846, 522, 470, 740, 769, 749, 645, 359, 618, 461, 615,
       462, 652, 357, 623, 801, 415, 712, 688, 379, 542, 666, 563, 798,
       638, 585, 416, 833, 644, 728, 776, 805, 532, 744, 734, 736, 356,
       407, 399, 552, 841, 401, 768, 457, 364, 519, 751, 384, 680, 609,
       437, 749, 758, 632, 544, 702])

In [45]:
length_of_employment = np.random.randint(low=0, high=60, size = 500)
length_of_employment

array([56, 34, 57, 23, 35,  0, 38,  5, 57, 36, 41,  1, 32,  6, 46, 27, 54,
       17, 39, 31, 31, 22, 33, 54, 18, 23,  3, 13, 46, 37, 13,  1, 49, 23,
       16, 33, 58,  8, 14,  8, 18,  8,  4, 42, 58, 15, 37, 59, 40, 22,  1,
       59, 55, 16, 51, 18, 14, 44, 28, 46, 23, 36,  7,  1, 29,  2, 30,  4,
       27, 44, 33, 59, 17,  8, 12, 21,  2,  2,  4, 32, 33, 30, 43, 19, 59,
        6, 57,  6, 26, 25, 46, 30, 48, 59, 10, 37, 32, 50, 21, 50, 51, 58,
       22,  0, 11, 33,  0, 20, 50, 26, 34,  9,  6, 39, 21, 33, 21,  5, 18,
       20, 18, 49, 11,  2,  6, 18, 54, 51, 11, 47, 43, 59, 23, 57, 38,  8,
       37, 36,  8, 54, 58, 50, 56, 38, 57, 48, 54, 57, 42, 56, 38,  5, 36,
       58, 28, 10, 31, 58,  5,  7, 24, 39, 21, 41, 44, 46, 21, 44, 56, 38,
       56, 29, 50, 24, 23, 38, 58,  2, 14, 23, 33, 34,  1, 57, 21, 52, 21,
       55,  0, 12, 47, 42, 32, 42,  2, 21, 40, 44, 31,  9, 22, 33, 22, 56,
       58, 50, 40, 45, 32,  7, 41, 14, 39, 50, 13,  0, 47,  9, 48, 42, 52,
       33, 26,  0, 58, 52, 50, 56, 28,  1, 50, 16,  2, 35, 48, 22,  2, 15,
       58,  2, 55, 30, 11,  2, 47, 40,  7,  2, 33, 53, 28,  1, 58,  7, 57,
       38, 10, 41,  3, 41, 52, 30, 15, 32,  5,  5, 30, 14, 35, 17,  0, 29,
       49,  7, 54,  3, 54, 22, 35,  6, 59, 23, 13, 14,  9, 53, 37,  7, 18,
        7,  5, 32, 54,  9,  6, 30, 28, 34,  4, 39, 57,  8, 58, 39, 50, 55,
       19, 49, 16,  8, 38, 57, 10, 28, 38, 44, 58, 34, 20, 47, 14, 20, 25,
       21, 51, 55, 26, 58, 47, 15, 47,  6, 51, 42, 12, 23,  4, 15, 23, 24,
       59, 41,  0,  1, 47,  9, 23, 11, 49, 31, 38, 16, 24,  2,  0, 21,  7,
        7,  0,  2, 28,  9, 13, 54, 12, 25, 45, 40,  5, 42, 15,  6, 33, 28,
       10, 59, 11, 35, 58, 31, 42, 50, 10,  3, 28, 47, 43, 29,  3, 44, 13,
       45, 39, 30, 29, 38, 28, 23, 13, 39, 17, 57, 30,  1,  5, 26, 35,  9,
        7, 28, 30, 11, 54, 25, 13, 11, 15, 29,  6, 10, 52, 26,  7,  6, 25,
       50, 29, 39, 27,  8, 42,  0, 38, 11, 50, 27, 45, 51, 31, 40, 23, 45,
       55, 17, 54, 27,  0, 12, 17,  5, 42, 25, 27, 48,  8, 38, 40, 15, 22,
       59,  8, 15,  1,  6, 51, 26,  0, 21, 25, 30, 12, 35,  9, 48,  2, 23,
       24, 51, 20, 26, 22, 57,  9, 41, 40,  6,  1,  6, 42,  2, 29,  1, 12,
       27, 23, 58, 27, 53, 36,  6])

In [46]:
length_of_current_residency = np.random.randint(low=0, high=36, size=500)
length_of_current_residency

array([ 7, 11, 29, 21,  5, 34, 22,  8, 13, 27, 16, 32, 17, 34, 25, 27, 15,
       26, 11, 19, 12, 26,  9,  7, 29, 13,  7, 29,  4, 20, 25, 18, 35, 33,
       25, 19, 32, 29,  1, 20, 11, 26, 34,  1, 31, 21, 14, 29,  2, 19, 21,
        2, 28,  5, 33, 14, 28, 31, 21, 31, 21, 10, 20, 25, 27, 25,  2, 25,
       24, 32, 24, 17, 26, 11, 35,  3, 32, 24, 21,  7,  0, 32,  9,  1, 27,
       21, 30, 19, 10,  6, 28,  6, 32, 14, 11,  4,  8,  6,  9,  5,  7, 28,
       12, 14, 30, 13, 22,  0,  3,  6, 28,  7, 14, 19,  4, 22, 11, 16, 21,
        9, 10,  6, 15,  7,  4,  4,  5, 28, 24, 17,  1, 19,  0, 14, 23, 19,
       14, 21, 26, 25, 11, 31,  1, 29,  2, 22, 27,  9, 26, 15, 18, 21, 11,
       30,  9, 22, 31, 22,  6, 24,  4, 11, 31, 20,  4, 30,  8, 35, 32, 25,
       11, 20,  4,  4, 25,  2,  7, 16,  4, 24,  9, 14, 12, 10, 17, 14, 16,
       27, 32, 18, 25,  0, 32, 21,  9, 28, 31,  6, 22, 13, 13, 23, 32, 24,
       21, 22,  3, 31, 12,  7, 17, 11, 11, 18,  1, 23, 16, 29, 33,  8, 25,
        5, 22, 14, 27, 24, 21,  0, 10,  2, 29, 34,  0, 30, 20, 18, 26, 18,
        8, 15, 22, 26,  5, 23,  7,  3, 25, 30, 27, 29,  2, 32, 14, 25, 16,
       10, 30, 34, 19, 26,  3, 33,  6, 27, 17,  3, 34, 16, 11, 26, 35, 31,
        9, 21, 23,  2, 33, 25,  4,  1,  4,  2,  8, 29, 35, 20,  3, 23, 12,
        8,  6, 22, 17, 25,  0, 19, 32, 12, 12, 11, 22, 32, 22, 24, 33, 29,
       15,  4, 32, 17, 25,  8, 24, 11, 31, 35, 35, 33, 13, 12, 14,  9, 24,
        8, 32, 33, 22,  9, 26,  5, 14, 14, 34, 18, 34, 26, 23, 18, 22,  1,
       33, 19, 25, 34,  1,  0, 19, 28,  1, 15, 26, 22,  3, 10, 32,  5, 18,
       16, 10, 16,  3, 24,  1, 16, 23, 28,  4, 21, 21, 31, 15, 15,  3, 22,
       25,  2, 33, 25, 30, 13, 13,  2, 19, 13, 26, 31,  2, 27, 28, 34,  2,
       31,  3, 17,  1, 26, 20, 29, 18,  0, 33, 17,  4,  4,  3, 25, 12, 27,
       27,  4,  8, 28, 14, 23, 16,  0, 11,  0, 35,  6, 30, 25, 27, 32,  2,
       23,  7, 15,  6, 35,  9, 19,  0,  9, 21, 34, 22, 21, 34, 18, 21,  2,
       16, 31, 25, 10,  3,  2, 35, 25, 26, 20,  5, 23, 31,  2, 32,  7, 25,
       16, 27, 11, 33, 27, 34, 30,  3,  9, 27,  1, 21, 30, 25, 35,  2,  4,
       28, 26,  4,  7, 31,  5, 24,  2, 16,  8, 29,  6, 17, 15, 16, 28, 30,
        8, 31,  4, 27, 14,  3,  1])

In [47]:
total_monthly_income = np.random.randint(2000,10000,500)
total_monthly_income

array([7920, 8748, 5582, 2418, 6637, 5720, 7666, 3984, 6385, 7202, 7373,
       5612, 5166, 8629, 9896, 7772, 8450, 9479, 6298, 9482, 5247, 7135,
       5804, 5875, 8312, 9869, 5421, 2312, 5228, 8044, 2792, 3391, 6278,
       8530, 6651, 5693, 5680, 9726, 2163, 8944, 2320, 5384, 4261, 6200,
       6862, 5560, 7002, 8793, 9428, 6928, 3648, 9275, 8041, 3088, 9593,
       9136, 7494, 3454, 7996, 2215, 7413, 9400, 3912, 4884, 4622, 4014,
       9878, 7753, 3757, 6230, 3945, 3820, 5014, 7471, 8684, 5428, 3770,
       3800, 7320, 5493, 4637, 7826, 7027, 9122, 8697, 4073, 8356, 7946,
       9081, 8259, 3226, 6162, 3473, 2035, 5272, 7898, 2694, 9237, 9498,
       5116, 4627, 6958, 7823, 3889, 3037, 9058, 4522, 8988, 9616, 9790,
       7133, 2456, 8019, 2157, 4536, 5000, 3813, 4920, 5187, 8364, 4861,
       6599, 3117, 3345, 9891, 7348, 7949, 4485, 5951, 5124, 6192, 7240,
       2644, 3820, 3206, 8653, 6000, 8321, 2706, 9391, 5166, 5119, 4884,
       6117, 9960, 5177, 6317, 4922, 5640, 8890, 4034, 3789, 7878, 8052,
       3919, 2959, 5468, 3008, 5880, 6752, 9462, 2766, 5471, 9536, 4275,
       5476, 2228, 6790, 8120, 8857, 3927, 5581, 4101, 8490, 9644, 3518,
       6280, 6696, 4697, 9484, 7318, 7993, 5667, 8313, 6566, 8518, 6248,
       4501, 8846, 8243, 5326, 6020, 4974, 5368, 6989, 5981, 5118, 6703,
       6743, 3216, 8643, 6311, 3983, 8664, 9140, 5616, 3489, 4278, 9905,
       4714, 5149, 4100, 5321, 2915, 7076, 8455, 2071, 6431, 9197, 6218,
       5802, 6792, 9478, 4547, 5686, 4020, 6775, 6612, 9648, 7571, 3411,
       9083, 8423, 9065, 6408, 2559, 7442, 3283, 4848, 2912, 8251, 4007,
       6868, 6631, 7474, 9457, 2002, 6044, 2921, 4773, 3337, 9676, 5589,
       8564, 8222, 9763, 2586, 4320, 8964, 6464, 9020, 8633, 7407, 6115,
       6226, 3585, 9122, 7093, 3792, 8885, 8423, 9081, 4947, 7880, 6472,
       8705, 5207, 8787, 5676, 4593, 4746, 4184, 7405, 4256, 7356, 6071,
       8066, 3383, 2236, 2216, 7021, 7369, 4804, 3223, 6757, 2112, 2198,
       4184, 4109, 5977, 5726, 8001, 5178, 5238, 5754, 7365, 4412, 8024,
       3955, 8271, 6781, 5751, 8797, 6660, 2501, 6781, 6256, 6791, 6097,
       9828, 3264, 7289, 4897, 6947, 9604, 2265, 7526, 6787, 4767, 6045,
       5456, 2818, 3209, 7075, 9297, 7645, 3387, 7712, 6547, 7839, 8579,
       4720, 2064, 9828, 8626, 2735, 5088, 5462, 4298, 3204, 3172, 8174,
       7810, 2668, 6377, 7905, 4985, 2596, 2243, 2285, 4684, 2171, 6819,
       5289, 2145, 5180, 7600, 8928, 9849, 9718, 5785, 7144, 4529, 7657,
       7017, 9557, 2324, 3553, 3298, 8186, 4076, 3256, 8386, 8758, 8476,
       3704, 5275, 3770, 8171, 6000, 8207, 6360, 7462, 3873, 6734, 8643,
       9644, 4745, 2043, 7122, 9126, 6895, 5063, 6645, 4765, 9504, 8683,
       7360, 4559, 4306, 9821, 6036, 3523, 6594, 6775, 5069, 6975, 3452,
       4386, 7584, 4395, 7943, 6019, 7067, 3169, 7595, 6116, 3102, 4770,
       2990, 6045, 8369, 3121, 4074, 7938, 8095, 8686, 6568, 3144, 8551,
       2495, 5495, 3850, 4662, 2588, 8938, 4300, 9066, 2681, 4539, 3360,
       4090, 9983, 4856, 2952, 2060, 5814, 7821, 2193, 5886, 6252, 8110,
       7194, 7744, 2743, 5548, 8066, 4814, 5573, 3174, 2353, 7154, 5590,
       8678, 8708, 4591, 4515, 8459, 2762, 8931, 7273, 8589, 3590, 3526,
       4586, 9501, 3627, 7944, 4429, 5826, 2869, 8378, 6538, 8354, 7794,
       5890, 2033, 6610, 8206, 8899])

In [48]:
debt_to_income_ratio = np.random.uniform(low=0.0, high=1, size=500)
debt_to_income_ratio = debt_to_income_ratio * 100

In [49]:
main = pd.DataFrame(data=[ficoscores,length_of_employment,length_of_current_residency,total_monthly_income,debt_to_income_ratio]).T
main

          0      1      2        3      4
0   593.000 56.000  7.000 7920.000 50.314
1   744.000 34.000 11.000 8748.000 24.693
2   845.000 57.000 29.000 5582.000 79.617
3   624.000 23.000 21.000 2418.000 81.520
4   832.000 35.000  5.000 6637.000 85.492
5   460.000  0.000 34.000 5720.000  2.727
6   541.000 38.000 22.000 7666.000 52.292
7   442.000  5.000  8.000 3984.000 50.136
8   721.000 57.000 13.000 6385.000 71.118
9   664.000 36.000 27.000 7202.000 92.655
10  478.000 41.000 16.000 7373.000 10.144
11  703.000  1.000 32.000 5612.000 88.476
12  735.000 32.000 17.000 5166.000 20.720
13  691.000  6.000 34.000 8629.000 91.789
14  411.000 46.000 25.000 9896.000 23.520
15  427.000 27.000 27.000 7772.000 60.307
16  775.000 54.000 15.000 8450.000 32.611
17  449.000 17.000 26.000 9479.000 78.872
18  543.000 39.000 11.000 6298.000 38.133
19  791.000 31.000 19.000 9482.000 81.764
20  532.000 31.000 12.000 5247.000 75.484
21  768.000 22.000 26.000 7135.000 93.882
22  845.000 33.000  9.000 5804.000 38.611
23  560.000 54.000  7.000 5875.000 47.402
24  401.000 18.000 29.000 8312.000 70.282
25  468.000 23.000 13.000 9869.000 26.317
26  751.000  3.000  7.000 5421.000 61.106
27  619.000 13.000 29.000 2312.000 32.851
28  633.000 46.000  4.000 5228.000 86.929
29  673.000 37.000 20.000 8044.000 46.230
..      ...    ...    ...      ...    ...
470 416.000 12.000 21.000 2353.000 43.460
471 833.000 35.000 30.000 7154.000 44.796
472 644.000  9.000 25.000 5590.000 75.461
473 728.000 48.000 35.000 8678.000 25.382
474 776.000  2.000  2.000 8708.000 70.769
475 805.000 23.000  4.000 4591.000 38.869
476 532.000 24.000 28.000 4515.000 73.356
477 744.000 51.000 26.000 8459.000  6.165
478 734.000 20.000  4.000 2762.000 48.351
479 736.000 26.000  7.000 8931.000 83.169
480 356.000 22.000 31.000 7273.000 57.145
481 407.000 57.000  5.000 8589.000 65.318
482 399.000  9.000 24.000 3590.000 74.056
483 552.000 41.000  2.000 3526.000 48.789
484 841.000 40.000 16.000 4586.000  9.111
485 401.000  6.000  8.000 9501.000 30.218
486 768.000  1.000 29.000 3627.000 94.225
487 457.000  6.000  6.000 7944.000 92.228
488 364.000 42.000 17.000 4429.000 91.895
489 519.000  2.000 15.000 5826.000 58.508
490 751.000 29.000 16.000 2869.000 31.101
491 384.000  1.000 28.000 8378.000 44.301
492 680.000 12.000 30.000 6538.000 83.166
493 609.000 27.000  8.000 8354.000 35.160
494 437.000 23.000 31.000 7794.000 65.297
495 749.000 58.000  4.000 5890.000 63.266
496 758.000 27.000 27.000 2033.000 35.648
497 632.000 53.000 14.000 6610.000 72.610
498 544.000 36.000  3.000 8206.000  8.562
499 702.000  6.000  1.000 8899.000  9.664

[500 rows x 5 columns]

In [50]:
main.to_csv("dataset.csv")